### ISSUE TITLE
What if the width, height are unknown until DOM loaded?

### ISSUE THREAD

**Issue by toklok** [gokcan/react-shimmer#1]
How could you give a specific width, height if these are unknown until the DOM Loaded?

**Comment by sercaninaler** [comment]
+1

**Comment by merelinguist** [comment]
@gokcan Having the same issue.

**Comment by gokcan** [comment]
Hello @merelinguist @sercaninaler @toklok,

Unfortunately, width and height must be provided to make the animation work.

However, you can use the newly introduced `fallback` prop for passing your own `Loader` component. Other internal stuff such as async loading & decoding logic will be handled by the library.

```js
function App(props) {
  return (
    <div>
      <Image
        src="https://example.com/test.jpg"
        fallback={<Spinner />}
      />
    </div>
  )
}
```
