### ISSUE TITLE
Getting Image failed to load error.

### ISSUE THREAD

**Issue by askerakbar** [gokcan/react-shimmer#111]
I implemented it using the following code:

```
 <div className="thumbnail">
            <Image
              src={post.image}
              fallback={<Shimmer width={100} height={100} />}
            />
            </div>
```

 but I'm getting this error in the browser:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/43740952/190243251-dd241fe4-ba77-47cc-bfce-b67ac5e92b36.png">

This is what I found when I inspected using dev tools:
`<span role="button" aria-label="Image failed to load">❌</span>`

**Comment by gokcan** [comment]
Hi, please make sure that the `src` prop value is valid.

In your specific example, it would be nice to add some precondition checks (null/empty src, invalid src, unreachable remote host) for `{post.image}`.
