### ISSUE TITLE
How to apply custom css classes to <img>?

### ISSUE THREAD

**Issue by fachryansyah** [gokcan/react-shimmer#123]
I want to add custom css into <img, there's no props to handle that

Edit--
I'm already tried add css into className props didn't work

```jsx
<Image
   src={item.image}
  width={512}
  height={512}
  alt="Berita1"
  className="rounded-xl"
   fadeIn={true}
   delay={2}
  fallback={<Shimmer width={512} height={512} />}
/>
```

<img width="591" alt="Screen Shot 2023-04-05 at 14 37 27" src="https://user-images.githubusercontent.com/14109765/230013772-718384ff-976b-41ce-b7df-719459dcfc4a.png">

**Comment by gokcan** [comment]
You may use `NativeImgProps`. Also, `alt` should be used with `NativeImgProps`.

Reference: https://github.com/gokcan/react-shimmer#properties

Example:

```ts 

<Image
  src={item.image}
  width={512}
  height={512}
  fadeIn={true}
  delay={2}
  fallback={<Shimmer width={512} height={512} />}
  NativeImgProps={{ alt="Berita1", className: "rounded-xl" }}
/>
```

**Comment by gokcan** [comment]
Also, see: https://github.com/gokcan/react-shimmer/issues/71
