### ISSUE TITLE
Not working properly with Owl carousel

### ISSUE THREAD

**Issue by tharindusenadeera** [gokcan/react-shimmer#40]
Implemented shimmer inside a owl carousel. If items exceeds four in owl carousel left image is not loading. only shimmer background image shows.
![Shimmer inside owl](https://user-images.githubusercontent.com/20136727/59268592-a8ec6f00-8c6a-11e9-91ed-5fa51a4985b9.png)

**Comment by gokcan** [comment]
Hi @tharindusenadeera, please share a working example of the issue (e.g. CodeSandbox link).
 I think it is related to the carousel component you use.
