### ISSUE TITLE
Any way to set the width and height to 100% of the container that the Image is in?

### ISSUE THREAD

**Issue by AizenSousuke** [gokcan/react-shimmer#59]
`<Image
						src={`${
							props.imageLink ??
							"http://loremflickr.com/480/272/default"
						}`}
						alt="button"
						fallback={<Shimmer width={`100%`} height={`100%`} />}
/>`

**Comment by gokcan** [comment]
Hey @AizenSousuke,

You'll need to pass actual **width** and **height** in pixels. 

[This lib ](https://github.com/okonet/react-container-dimensions)is quite useful for achieving what you want to achieve.

Some implementation like below should work:

```js
import React from 'react'
import Image, { Shimmer } from 'react-shimmer
import ContainerDimensions from 'react-container-dimensions'

export const App = ({ src }) => (
    <div>
        <ContainerDimensions>
           {({ width, height }) => 
            <Image
             src={src}
             fallback={<Shimmer width={width} height={height} />}
            />
           }
        </ContainerDimensions>
    <div>
)
```

**Comment by AizenSousuke** [comment]
Thank you!

**Comment by Sinakhx** [comment]
> Hey @AizenSousuke,
> 
> You'll need to pass actual **width** and **height** in pixels if you want to use ` <Shimmer />` as a fallback.
> 
> [This lib ](https://github.com/okonet/react-container-dimensions)is quite useful for achieving what you want to achieve. An implementation like below should work:
> 
> ```js
> import React from 'react'
> import Image, { Shimmer } from 'react-shimmer
> import ContainerDimensions from 'react-container-dimensions'
> 
> export const App = ({ src }) => (
>     <div>
>         <ContainerDimensions>
>            {({ width, height }) => 
>             <Image
>              src={src}
>              fallback={<Shimmer width={width} height={height} />}
>             />
>            }
>         </ContainerDimensions>
>     <div>
> )
> ```

this works, however I don't prefer to use another third-party library in order to just set dynamic dimensions. Neither is it preferable to add a container element to the image or get our hands dirty working with refs. It would be so nice to support this natively.
