### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by Wekios** [gokcan/react-shimmer#64]
Hi, I'm conditionally rendering a component, a modal mini-cart of sorts, and I'm getting a 
`Can't perform a React state update on an unmounted component ...` error 
if I close the cart before the image has been loaded.
As you can see on the screenshot, the issue is inside Image component that you're exporting. 
Is this fixable? Cheers!

![Screenshot_7](https://user-images.githubusercontent.com/28904821/83556360-075fcc80-a510-11ea-9705-75392fcb9273.jpg)

**Comment by gokcan** [comment]
Hi, thank you for the report. You may check out the latest version `3.1.1` from npm.
