### ISSUE TITLE
How to add class name to <Image> Component

### ISSUE THREAD

**Issue by muhammadyana** [gokcan/react-shimmer#71]
i've try to add `className` in `<Image>` component, but it doesn't work. here my code
`<Image`
      `src={this.props.imageUrl}`
      `fallback={<Shimmer width={800} height={600} />}`
      `className={this.props.className}`
` />`

**Comment by gokcan** [comment]
You should use **NativeImgProps**:

```js
<Image
   src={this.props.imageUrl}
   fallback={<Shimmer width={800} height={600} />}
   NativeImgProps={{ className: this.props.className }}
/>
```
