### ISSUE TITLE
Repeated network request

### ISSUE THREAD

**Issue by zerofront** [gokcan/react-shimmer#72]
![image](https://user-images.githubusercontent.com/19327366/90776237-72a98580-e32c-11ea-83c6-19edc7196b96.png)

If I set disable cache in chrome devtool, you can see that it will request double time

**Comment by gokcan** [comment]
Hi @zerofront,

Instead of a custom cache implementation, this library depends on native browser cache.

**Comment by zerofront** [comment]
@gokcan thanks for your reply! 

image in `loadImage` function  and image in `render` function are different image instance. 

Is there cache  for decode?  Will the browser decode the same URL image only once?
