### ISSUE TITLE
alt Tag is missing from image props

### ISSUE THREAD

**Issue by Giggiux** [gokcan/react-shimmer#74]
for SEO optimization the image's [`alt`](https://www.w3schools.com/tags/att_img_alt.asp) tag is needed. 

It would be optimal to have it on the Image component.

**Comment by gokcan** [comment]
You may use the `NativeImgProps` prop to pass `alt` to the underlying `<img>`.

**Comment by arifals27** [comment]
> You may use the `NativeImgProps` prop to pass `alt` to the underlying `<img>`.

can you give example how to use NativeImgProps

**Comment by Giggiux** [comment]
@arifals27 I haven't used this in 2 years now, but I guess you may just do something like `<Image NativeImgProps={{alt:"my alt text"}}>`

[here is the line that adds that NativeImgProps to the Image props](https://github.com/gokcan/react-shimmer/blob/e1d42c429e5ba5f5d5990e5a631546d59480f2d6/src/Image.tsx#L22)

**Comment by gokcan** [comment]
Example usage:

```ts

import React from 'react'
import { Image, Breathing } from 'react-shimmer'

function App() {
  return (
    <div>
      <Image
        src='https://source.unsplash.com/random/800x600'
        fallback={<Breathing width={800} height={600} />}
        NativeImgProps={{ alt: "Descriptive text." }}
      />
    </div>
  )
}
```

**Comment by rajnikantwebdev** [comment]
Hey thank you for this wonderful package, but i have a question regarding alt text.  I am using it the same way as you mentioned but the alt text is not visible.
<img width="587" alt="alttext" src="https://github.com/gokcan/react-shimmer/assets/112321572/94bec496-9221-43ca-8623-964da4f69a2c">

in browser it is visible something like this

<img width="353" alt="alttext2" src="https://github.com/gokcan/react-shimmer/assets/112321572/234f4c04-cf4a-4b4a-a06d-73eee756164c">
