### ISSUE TITLE
unit tests broke

### ISSUE THREAD

**Issue by akinncar** [gokcan/react-shimmer#77]
When I use react-shimmer and test a component with that, my tests broke.

![Console error](https://user-images.githubusercontent.com/42688281/108885880-1713c980-75e7-11eb-8355-0c592441dc26.jpeg)

has anyone had this problem? found it in version 17 of React

**Comment by gokcan** [comment]
Hey @akinncar, could you install the latest version of react-shimmer?

I have greatly improved the module build process: #90, most of the issues should be gone.
