### ISSUE TITLE
syntaxError: Cannot use import statement outside a module @ eval (webpack internal

### ISSUE THREAD

**Issue by labaran1** [gokcan/react-shimmer#85]
<b>In my nextjs application , i install this package <b>

i also used it like this 
``` 
import Image,  { Shimmer } from "react-shimmer";
```
```js
 <Image
   src={currentImage}
    fallback={<Shimmer width={500} height={540} />}
     />
```

**Comment by gokcan** [comment]
Hey @labaran1 , could you install the latest version of react-shimmer?

I have greatly improved the module build process: #90
