### ISSUE TITLE
Problem with module build?

### ISSUE THREAD

**Issue by dkadrios** [gokcan/react-shimmer#87]
Version: 3.1.1

package.json has the line:
```
"module": "dist/index.module.js",
```

...but that file doesn't seem to exist in the built dist folder though (e.g. node_modules/react-shimmer/dist/index.module.js)

I'm encountering errors related to this while trying to build with Parcel.
```
@parcel/resolver-default: Could not load './dist/index.module.js' from module 'react-shimmer' found in package.json#module
/Users/username/git/project/node_modules/react-shimmer/package.json:22:13
  21 |   "main": "dist/index.js",
> 22 |   "module": "dist/index.module.js",
>    |             ^^^^^^^^^^^^^^^^^^^^^^ './dist/index.module.js' does not exist, did you mean './dist/index.d.ts'?'
  23 |   "source": "src/index.ts",
  24 |   "typings": "dist/index.d.ts",
```

**Comment by gokcan** [comment]
Hey @dkadrios, could you install the latest version of react-shimmer?

I have greatly improved the module build process: https://github.com/gokcan/react-shimmer/pull/90

**Comment by dkadrios** [comment]
Sure, I can try it out later this week
